replicaCount: 1
image:
  repository: mindconnectacr.azurecr.io/mindconnect/payment-service
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 5004
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
