replicaCount: 2
image:
  repository: mindconnectacr.azurecr.io/mindconnect/api-gateway
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 3000
ingress:
  enabled: true
  host: mindconnect.172.214.66.167.nip.io
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
