apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: mindconnect
  labels:
    app: api-gateway
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: API_GATEWAY_PORT
              value: "3000"
            - name: AUTH_SERVICE_PORT
              value: "5001"
            - name: USER_SERVICE_PORT
              value: "5002"
            - name: SOCIAL_SERVICE_PORT
              value: "5003"
            - name: PAYMENT_SERVICE_PORT
              value: "5004"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mindconnect-secrets
                  key: JWT_SECRET
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
