apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kvikash668/MindConnect.git
    targetRevision: main
    path: helm/charts/api-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: mindconnect
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
