replicaCount: 1
image:
  repository: mindconnectacr.azurecr.io/mindconnect/auth-service
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 5001
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

port: 5001

port: 5001
